### ISSUE TITLE
Port to web extension

### ISSUE THREAD

**Issue by wildskyf** [kidwm/dictionary-panel#2]
FYI: 可以用 `browser.windows.create({ type: 'popup' })` 做出類似的效果

**Comment by wildskyf** [comment]
順帶一提，這裡有個 bug，附上 workaround 連結。
https://bugzilla.mozilla.org/show_bug.cgi?id=1402110#c4

**Comment by kidwm** [comment]
done by 3d752d01400298173f000b358e7e8f58b79a53a3
